name: Code Review on Request

permissions:
  contents: read
  pull-requests: write

on:
  issue_comment:
    types: [created]  # コメントが作成されたときにトリガー

jobs:
  review:
    if: contains(github.event.comment.body, '/review')  # コメントに /review が含まれているかをチェック
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run GPT-based code review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Japanese  # 日本語でレビューを返す
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4  # 使用するモデル
          PROMPT: |
            プルリクエストに含まれるコードにおいて、バグ、改善点、パフォーマンス問題がないか確認し、必要であれば指摘してください。
          top_p: 1
          temperature: 1
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000  # コード差分の最大長

