name: Code Review on Request

permissions:
  contents: read
  pull-requests: write
  issues: write  # コメントを投稿するための権限

on:
  issue_comment:
    types: [created]  # コメントが作成されたときにトリガー

jobs:
  review:
    if: contains(github.event.comment.body, '/review')  # コメントに /review が含まれているかをチェック
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ChatGPTのコードレビューを実行し、その出力をキャプチャする
      - name: Run GPT-based code review
        id: run_review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4o-mini  # モデルを gpt-4o-mini に変更
          PROMPT: |
            プルリクエストに含まれるコードにおいて、バグ、改善点、パフォーマンス問題がないか確認し、必要であれば指摘してください。
          top_p: 1
          temperature: 1
          # max_tokens: を取り除き、制限なしに

      # ChatGPTの出力をプルリクエストにコメントとして投稿する
      - name: Post review comment if successful
        if: success()  # AIレビューが成功した場合に実行
        run: |
          # 標準出力から結果を取得
          review_result=$(cat $GITHUB_WORKSPACE/output.txt)
          
          if [ -z "$review_result" ]; then
            review_result="AIレビュー結果がありませんでした。"
          fi

          echo "Review result: $review_result"
          
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\": \"$review_result\"}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments

      - name: Post failure comment if review fails
        if: failure()  # AIレビューが失敗した場合に実行
        run: |
          echo "AIレビューに失敗しました。"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\": \"AIレビューに失敗しました。ログを確認してください。\"}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments
