name: PR Review Workflow
on:
  # PRに対しActionsを動作させる
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    # ActionsからPRに対しコメントするために必要
    permissions:
      pull-requests: write

    steps:
    # レビュースクリプト実行のためコードをチェックアウトする
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install openai
        pip install PyGithub
    - name: Run script
      run: python scripts/code_review_script.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REPOSITORY: "your-username/your-repository-name"
        PR_NUMBER: ${{ github.event.number }}